export const HTTP_STATUS = {
  UP: 'UP',
  DOWN: 'DOWN',
  SLOW: 'SLOW'
};

export const ERROR_TYPES = {
  TIMEOUT: 'TIMEOUT',
  DNS_ERROR: 'DNS_ERROR',
  CONNECTION_REFUSED: 'CONNECTION_REFUSED',
  HTTP_ERROR: 'HTTP_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  RESPONSE_VALIDATION_ERROR: 'RESPONSE_VALIDATION_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
};

export const MONITOR_CONFIG = {
  DEFAULT_TIMEOUT: 5000,
  DEFAULT_RETRIES: 3,
  DEFAULT_CHECK_INTERVAL: 60,
  SLOW_RESPONSE_THRESHOLD: 3000,
  MAX_CONCURRENT_CHECKS: 10,
  CRON_EXPRESSION: '*/1 * * * *'
};

export const ALERT_CONFIG = {
  COOLDOWN_PERIOD: 300000,
  MAX_ALERTS_PER_HOUR: 5
};